apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: helved-peisen
  namespace: helved
  labels:
    team: helved
spec:
  image: {{ image }}
  port: 3000
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      cpu: 100m
    requests:
      cpu: 100m
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
  ingresses:
    - 'https://peisen.intern.dev.nav.no'
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: utsjekk
        - application: peisschtappern
  env:
    - name: NEXT_PUBLIC_HOSTNAME
      value: "https://peisen.intern.dev.nav.no"
    - name: API_SCOPE
      value: "api://dev-gcp.helved.peisschtappern/.default"
    - name: API_BASE_URL
      value: "http://peisschtappern"
    - name: NEXT_PUBLIC_SHOW_MESSAGE_PAYLOAD
      value: "true"
  liveness:
    path: /internal/is-alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is-ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
