apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: helved-peisen
  namespace: helved
  labels:
    team: helved
spec:
  image: {{ image }}
  port: 3000
  replicas:
    min: 1
    max: 1
  resources:
    limits:
      memory: 256Mi
    requests:
      memory: 256Mi
      cpu: 30m
  observability:
    autoInstrumentation:
      enabled: true
      runtime: nodejs
    logging:
      destinations:
        - id: loki
        - id: elastic
  ingresses:
    - 'https://peisen.intern.dev.nav.no'
  azure:
    application:
      enabled: true
      allowAllUsers: true
    sidecar:
      enabled: true
  accessPolicy:
    outbound:
      rules:
        - application: utsjekk
        - application: peisschtappern
        - application: vedskiva
        - application: logging
          namespace: nais-system
  env:
    - name: NEXT_PUBLIC_HOSTNAME
      value: "https://peisen.intern.dev.nav.no"
    - name: API_SCOPE
      value: "api://dev-gcp.helved.peisschtappern/.default"
    - name: API_BASE_URL
      value: "http://peisschtappern"
    - name: UTSJEKK_API_SCOPE
      value: "api://dev-gcp.helved.utsjekk/.default"
    - name: UTSJEKK_BASE_URL
      value: "http://utsjekk"
    - name: VEDSKIVA_API_SCOPE
      value: "api://dev-gcp.helved.vedskiva/.default"
    - name: VEDSKIVA_BASE_URL
      value: "http://vedskiva"
  liveness:
    path: /internal/is-alive
    initialDelay: 10
    timeout: 5
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /internal/is-ready
    initialDelay: 10
    periodSeconds: 5
    timeout: 5
